title: WordPress Self-Help  
email: contact@leapsparkagency.com
description:
baseurl: ""
url: "https://leap-spark.github.io/wordpress-self-help/"

# Social
githubUsername:
twitterUsername:
dribbbleUsername:
codepenUsername:

# Build settings
markdown: kramdown

#themeColor: gray
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
